
name: CI/CD Backend
on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/BACKEND/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
       
      - name: Running tests
        run: cd BACKEND && npm run test
